### PR TITLE
Add handling for unicode escape in JsonYamlConverter

### PR DESCRIPTION
**Pull request by sasakirione**
## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] New feature or enhancement
- [ ] UI change (please include screenshot!)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Internationalization and localization
- [ ] Other (please describe):

## What is the current behavior?

In the feature that converts JSON to YAML, Unicode escapes included in the values are automatically converted.

Issue Number: https://github.com/DevToys-app/DevToys/issues/1112

## What is the new behavior?

In the feature that converts JSON to YAML, Unicode escapes included in the values are automatically converted.

## Other information

 - Unicode escapes are output in lowercase by default.

## Quality check

Before creating this PR:

- [x] Did you follow the code style guideline as described in [CONTRIBUTING.md](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md)
- [x] Did you build the app and test your changes?
- [ ] Did you check for accessibility? On Windows, you can use Accessibility Insights for this.
- [ ] Did you verify that the change work in Release build configuration
- [x] Did you verify that all unit tests pass
- [ ] If necessary and if possible, did you verify your changes on:
   - [x] Windows
   - [ ] macOS
   - [ ] Linux

### CODE REVIEW

**Comment by veler** [comment]
Hello,

Thanks for this pull request.

I tried a few scenarios and I found an issue: When having `{"name": "doré"}` as JSON input, I'd expect `name: doré` but got `name: dor\u00e9`.

**Comment by sasakirione** [comment]
Hello,
Thank you for pointing that out! 
I have also confirmed it on my end.
I'll take another look at it.

**Comment by sasakirione** [comment]
I have made corrections to ensure that both the strings that are escaped and the escape sequences are correctly output!

**Comment by veler** [comment]
Thanks for the update! It looks good to me :D Thank you very much for this contribution!

**Pull request merged**
