### PR TITLE
Kleine Verbesserungen und Korrekturen an Übersetzung

### PR DESCRIPTION
**Pull request by Sencaid**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] New feature or enhancement
- [ ] UI change (please include screenshot!)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Internationalization and localization
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

## Quality check

Before creating this PR:

- [ ] Did you follow the code style guideline as described in [CONTRIBUTING.md](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md)
- [ ] Did you build the app and test your changes?
- [ ] Did you check for accessibility? On Windows, you can use Accessibility Insights for this.
- [ ] Did you verify that the change work in Release build configuration
- [ ] Did you verify that all unit tests pass
- [ ] If necessary and if possible, did you verify your changes on:
   - [ ] Windows
   - [ ] macOS
   - [ ] Linux

### CODE REVIEW

**Comment by veler** [comment]
Hi,
Please do translation changes on Crowdin instead of directly in the code. Please follow the steps indicated here: https://github.com/DevToys-app/DevToys.Tools/blob/main/CONTRIBUTING.md#internationalization-and-localization
Thanks

**Comment by Sencaid** [comment]
This would be my last Commit, can you give the Source to someone or can you do it yourself please. I dont want to create a Crowdin Account only for this little Commit

**Comment by Sencaid** [comment]
> This would be my last Commit, can you give the Source to someone or can you do it yourself please. I dont want to create a Crowdin Account only for this little Commit. (Im the one who translated everything to German)

Is your Decision still the same ? @veler

**Comment by Sencaid** [comment]
Can you please make an exception this time? These commits are just a few fixes. I would definitely create a crowdin account for more commits. @veler

**Comment by Sencaid** [comment]
Ok I did it on Crowdin. You can delete this pull

**Pull request closed without merging**
